### ISSUE TITLE
Question on sorted merge step of mergingDigest algorithm

### ISSUE THREAD

**Issue by schatterjee10** [tdunning/t-digest#102] opened 2018-02-09 22:28 UTC
In Java implementation of T-Digest algorithm, the sorting is done based solely on mean. The weight is not taken into account. If we have many repeated samples, we could end up getting sorted order like this : 

Mean   weight
2.5       10
2.5        5
2.5       1
3.5       20

Depending upon how sorting is done, the order could also be different : 

Mean  weight
2.5     1
2.5      10
2.5       5
3.5       20

When we recreate new merged bins, does it matter which of the above order is obtained from sorting? Clearly the total number of bins used will be different if the order of (mean, weight) are not exactly the same.

**Comment by tdunning** [comment] 2021-01-25 05:49
This is a very important question!

Your question together with two other issues got me to looking more carefully at what happens with repeated values and I actually found a significant bug as a result. Commit coming shortly.

The problem is that the sort is unstable so that with lots of repeated values, heavy centroids can exchange places with very light ones with the same mean. That leads to violation of t-digest invariants.

I have a fix coming shortly and will close this issue at that time. Sorry for the slow response but I am glad you asked this excellent question even though I didn't understand the implications at first.

Good questions are sometimes almost as good as good answers!

Thanks!

**Comment by tdunning** [comment] 2021-01-26 01:15
Fixed by adopting stable sorting in eca1125a39c13e918d7054105dc89bcda11cfa44

**Closed by tdunning** 2021-01-26 01:15 UTC
