### ISSUE TITLE
Adding an empty tdigest to a non-empty t-digest results in inconsistent quantiles

### ISSUE THREAD

**Issue by samarthjain** [tdunning/t-digest#114] opened 2018-09-11 19:05 UTC
```Java
@Test
    public void testQuantile() throws Exception {
        for (int i = 1; i < 100; i++) {
            TDigest hist = new MergingDigest(50);
            hist.add(1.0, 1);
            hist.add(2.0, 2);
            hist.add(2.0, 2);
            hist.add(2.0, 2);
            hist.add(3.0, 2);
            hist.add(3.0, 1);
            hist.add(3.0, 1);
            hist.add(4.0, 1);
            hist.add(5.0, 1);
            hist.add(6.0, 1);
            hist.add(7.0, 1);
            TDigest hist2 = new MergingDigest(50);
            hist2.add(hist);
            System.out.println(hist2.quantile(0.5));
        }
    }
```

On running the above test, one can see that the quantile is reported as 2.75 or 3.0. The behavior is same when using AVLTreeDigest too. 

This seems to be happening because of the following shuffle in AbstractTdigest#add() method - https://github.com/tdunning/t-digest/blob/26ddfd6ee227e053fb42288edbca88ddab1372b6/core/src/main/java/com/tdunning/math/stats/AbstractTDigest.java#L141

@tdunning - what was the reason the shuffle was added?

**Comment by tdunning** [comment] 2021-01-18 23:39
Sorry to ignore you for so long.

I am checking on this issue now.

**Comment by tdunning** [comment] 2021-01-18 23:46
On the surface here, you have added samples with weight > 1 which resulted in an invalid t-digest.

Splitting your adds into two unit adds gives the right behavior, but that may be due to the fact that there are very few samples so all of them are stored explicitly in the digest.

I don't remember the rationale for the shuffle. I think it is sloppy from the current point of view, but it may have had a good rational from the standpoint of avoiding ordering bias. This would particularly affect the`AVLTreeDigest`, I think.

Still digging.

**Comment by tdunning** [comment] 2021-01-19 06:54
I have replicated this with a test case by inserting the data multiple times. Without that, the t-digest retains all of the data points intact and gives exact answers.

Oddly enough, however, even after suppressing the shuffle things aren't simple. An unmerged t-digest gives the same results as a merged one, but it doesn't get consistent results when repeating the same data. I think that this has to do with alternating orders or some such in the merging digest, but I don't have a smoking gun yet.

**Comment by tdunning** [comment] 2021-01-25 05:38
I just wanted to say ...

Your question together with two other issues got me to looking more carefully at what happens with repeated values and I actually found a significant bug as a result. Commit coming shortly.

Good questions are sometimes almost as good as good answers!

The variability in the answers you were getting is intentional. The shuffle is still a bit of a mystery, but it is almost certainly there to mitigate effects of ordering. There is also some non-determinism in the sorting since the quicksort picks a random pivot.

So that explains the fact of the variability.

But ... in looking at your test case and simplifying it, I find that there was a serious bug to do with repeated values. The issue is that with lots of repeated values near q=0 and q=1, there will be centroids with the same mean but different weights. The sort, however, only looked at the mean which meant that sometimes the weighty centroids would sort before the lighter ones. That caused a violation of the t-digest size invariant can resulted in bad accuracy. The same effect could result in poor accuracy near the median because the heaviest centroid might be sorted away from where it should be.

I have a fix now and some test cases, but I wanted to thank you for the question that led to finding all of this. I will credit this issue as I commit the fix.

Thanks!

**Comment by tdunning** [comment] 2021-01-26 01:14
This should be fixed with eca1125a39c13e918d7054105dc89bcda11cfa44

**Closed by tdunning** 2021-01-26 01:14 UTC

**Comment by samarthjain** [comment] 2021-01-26 06:28
Thanks for your updates and fixes, @tdunning!

It would be good to figure out if we can get rid of the shuffle for good. Merging of two t-digests happens to be on a hot code path of various compute engines (like Druid, Presto) that deal with merging of t-digest like sketches as part of producing results for a group by/aggregate style query. So any reduction in CPU cycles spent during the merges would be helpful. It sounds like MergingDigest doesn't need the shuffle. So maybe we can get rid of it only for the MergingDigest?

**Comment by tdunning** [comment] 2021-01-26 06:36
I have removed the shuffle for now pending quality testing.
